In [3]:
import pandas as pd

In [4]:
glogs = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/game_logs.csv')

# Convert date column to datetime, filters out dates before 2005 
glogs['date'] = pd.to_datetime(glogs['date'], format=r'%Y%m%d')
glogs = glogs[glogs['date'].dt.year >= 2005]
glogs['year'] = glogs['date'].dt.year

# Specify columns to keep for analysis
glogs = glogs[['date', 'year', 'day_of_week', 'v_name', 'v_league', 'v_game_number', 'h_name', 'h_league', 
               'h_game_number', 'v_score', 'h_score', 'day_night', 'park_id', 'attendance']]

# Remove international ballparks that were only used for one random game
glogs = glogs[~glogs['park_id'].isin(['SYD01', 'TOK01', "SJU01", 'FTB01', 'LBV01'])]
glogs.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,day_night,park_id,attendance
0,2005-04-03,2005,Sun,BOS,AL,1,NYA,AL,1,2,9,N,NYC16,54818.0
1,2005-04-04,2005,Mon,OAK,AL,1,BAL,AL,1,0,4,D,BAL12,48271.0
2,2005-04-04,2005,Mon,CLE,AL,1,CHA,AL,1,0,1,D,CHI12,38141.0
3,2005-04-04,2005,Mon,KCA,AL,1,DET,AL,1,2,11,D,DET05,44105.0
4,2005-04-04,2005,Mon,MIN,AL,1,SEA,AL,1,1,5,D,SEA03,46249.0

In [5]:
# Rename stadium names in park_id column
# STL09 = Busch Stadium II
# STL10 = Busch Stadium III
# NYC16 = Old Yankee Stadium
# NYC17 = Shea Stadium
# NYC20 = Citi Field
# NYC21 = New Yankee Stadium
# WAS10 = RFK Stadium
# WAS11 = Nationals Park
# MIA01 = Sun Life Stadium
# MIA02 = Marlins Park
# MIN03 = Metrodome
# MIN04 = Target Field
glogs['park_id'] = glogs['park_id'].replace({'ANA01': 'Angel Stadium',
                                             'ARL02': 'Globe Life Field',
                                             'ATL02': 'Turner Field',
                                             'BAL12': 'Camden Yards',
                                             'BOS07': 'Fenway Park',
                                             'CHI11': 'Wrigley Field',
                                             'CHI12': 'US Cellular Field',
                                             'CIN09': 'Great American Ballpark',
                                             'CLE08': 'Progressive Field',
                                             'DEN02': 'Coors Field',
                                             'DET05': 'Comerica Park',
                                             'HOU03': 'Minute Maid Park',
                                             'KAN06': 'Koffman Stadium',
                                             'LOS03': 'Dodger Stadium',
                                             'MIA01': 'Sun Life Stadium',
                                             'MIA02': 'Marlins Park',
                                             'MIL06': 'Miller Park',
                                             'MIN03': 'Metrodome',
                                             'MIN04': 'Target Field',
                                             'NYC16': 'Old Yankee Stadium',
                                             'NYC17': 'Shea Stadium',
                                             'NYC20': 'Citi Field',
                                             'NYC21': 'New Yankee Stadium',
                                             'OAK01': 'Coliseum',
                                             'PHI13': 'Citizens Bank Park',
                                             'PHO01': 'Chase Field',
                                             'PIT08': 'PNC Park',
                                             'SAN02': 'Petco Park',
                                             'SEA03': 'Safeco Field',
                                             'SFO03': 'AT&T Park',
                                             'STL09': 'Busch Stadium II',
                                             'STL10': 'Busch Stadium III',
                                             'STP01': 'Tropicana Field',
                                             'TOR02': 'Rogers Centre',
                                             'WAS10': 'RFK Stadium',
                                             'WAS11': 'Nationals Park',
                                             })
glogs.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,day_night,park_id,attendance
0,2005-04-03,2005,Sun,BOS,AL,1,NYA,AL,1,2,9,N,Old Yankee Stadium,54818.0
1,2005-04-04,2005,Mon,OAK,AL,1,BAL,AL,1,0,4,D,Camden Yards,48271.0
2,2005-04-04,2005,Mon,CLE,AL,1,CHA,AL,1,0,1,D,US Cellular Field,38141.0
3,2005-04-04,2005,Mon,KCA,AL,1,DET,AL,1,2,11,D,Comerica Park,44105.0
4,2005-04-04,2005,Mon,MIN,AL,1,SEA,AL,1,1,5,D,Safeco Field,46249.0

In [6]:
# Rename team abbreviations for consistency with conventional abbreviations
glogs['v_name'] = glogs['v_name'].replace({'ANA':'LAA',
                         'CHA':'CHW',
                         'CHN':'CHC',
                         'FLO':'MIA',
                         'KCA':'KC',
                         'LAN':'LAD',
                         'NYA':'NYY',
                         'NYN':'NYM',
                         'SDN':'SD',
                         'SFN':'SF',
                         'SLN':'STL',
                         'TBA':'TB',
                         'WAS':'WSH'})
glogs['h_name'] = glogs['h_name'].replace({'ANA':'LAA',
                         'CHA':'CHW',
                         'CHN':'CHC',
                         'FLO':'MIA',
                         'KCA':'KC',
                         'LAN':'LAD',
                         'NYA':'NYY',
                         'NYN':'NYM',
                         'SDN':'SD',
                         'SFN':'SF',
                         'SLN':'STL',
                         'TBA':'TB',
                         'WAS':'WSH'})
glogs['h_name'].sort_values().unique()

array(['ARI', 'ATL', 'BAL', 'BOS', 'CHC', 'CHW', 'CIN', 'CLE', 'COL',
       'DET', 'HOU', 'KC', 'LAA', 'LAD', 'MIA', 'MIL', 'MIN', 'NYM',
       'NYY', 'OAK', 'PHI', 'PIT', 'SD', 'SEA', 'SF', 'STL', 'TB', 'TEX',
       'TOR', 'WSH'], dtype=object)

In [8]:
# Add column 'location'
glogs['location'] = glogs['h_name'].map({'ARI': 'Arizona', 'ATL': 'Atlanta', 'BAL': 'Baltimore', 'BOS': 'Boston', 'CHC': 'Chicago',
                                         'CHW': 'Chicago', 'CIN': 'Cincinatti', 'CLE': 'Cleveland', 'COL': 'Colorado', 'DET': 'Detroit',
                                         'HOU': 'Houston', 'KC': 'Kansas City', 'LAA': 'Los Angeles', 'LAD': 'Los Angeles', 'MIA': 'Miami',
                                         'MIL': 'Miluakee', 'MIN': 'Minnesota', 'NYM': 'New York', 'NYY': 'New York', 'OAK': 'Oakland',
                                         'PHI': 'Philadelphia', 'PIT': 'Pittsburgh', 'SD': 'San Diego', 'SEA': 'Seattle',
                                         'SF': 'San Francisco', 'STL': 'St. Louis', 'TB': 'Tampa Bay', 'TEX': 'Texas', 'TOR': 'Toronto',
                                         'WSH': 'Washington, D.C.'
})
glogs.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,day_night,park_id,attendance,location
0,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,9,N,Old Yankee Stadium,54818.0,New York
1,2005-04-04,2005,Mon,OAK,AL,1,BAL,AL,1,0,4,D,Camden Yards,48271.0,Baltimore
2,2005-04-04,2005,Mon,CLE,AL,1,CHW,AL,1,0,1,D,US Cellular Field,38141.0,Chicago
3,2005-04-04,2005,Mon,KC,AL,1,DET,AL,1,2,11,D,Comerica Park,44105.0,Detroit
4,2005-04-04,2005,Mon,MIN,AL,1,SEA,AL,1,1,5,D,Safeco Field,46249.0,Seattle

In [47]:
# Add time column - not needed anymore
# glogs['time'] = glogs['day_night'].apply(lambda x: pd.to_datetime('13:00:00') if x == 'D' else pd.to_datetime('19:00:00'))
# glogs['time'] = glogs['time'].dt.time
# glogs.head()

In [9]:
# Read in weather data for NL East teams
weather_PHI = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/weather_files/weather_PHI.csv')
weather_PHI['date'] = pd.to_datetime(weather_PHI['date'])
weather_PHI['location'] = 'Philadelphia'

weather_NYM = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/weather_files/weather_NYM.csv')
weather_NYM['date'] = pd.to_datetime(weather_NYM['date'])
weather_NYM['location'] = 'New York'

weather_ATL = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/weather_files/weather_ATL.csv')
weather_ATL['date'] = pd.to_datetime(weather_ATL['date'])
weather_ATL['location'] = 'Atlanta'
weather_ATL

weather_MIA = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/weather_files/weather_MIA.csv')
weather_MIA['date'] = pd.to_datetime(weather_MIA['date'])
weather_MIA['location'] = 'Miami'

weather_WSH = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/weather_files/weather_WSH.csv')
weather_WSH['date'] = pd.to_datetime(weather_WSH['date'])
weather_WSH['location'] = 'Washington, D.C.'



# Concatenate NL East weather vertically
weather_nl_east = pd.concat([weather_PHI, weather_NYM, weather_ATL, weather_MIA, weather_WSH], ignore_index=True)
weather_nl_east

            date  temperature_2m_max (°F)  rain_sum (inch)          location
0     2005-04-03                     49.6            0.272      Philadelphia
1     2005-04-04                     59.8            0.000      Philadelphia
2     2005-04-05                     66.0            0.000      Philadelphia
3     2005-04-06                     76.8            0.000      Philadelphia
4     2005-04-07                     73.7            0.122      Philadelphia
...          ...                      ...              ...               ...
21005 2016-09-29                     70.7            1.461  Washington, D.C.
21006 2016-09-30                     66.9            0.094  Washington, D.C.
21007 2016-10-01                     68.0            0.181  Washington, D.C.
21008 2016-10-02                     71.7            0.000  Washington, D.C.
21009 2016-10-03                     74.4            0.008  Washington, D.C.

[21010 rows x 4 columns]

In [10]:
#read in weather data for NL Central teams
weather_CHC = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Chicago_Cubs.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_CHC['date'] = pd.to_datetime(weather_CHC['time'])
weather_CHC['location'] = 'Chicago'


weather_CIN = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Cincinnati_Reds.csv',
    skiprows=3,  # Skips the first 3 rows of the file) 
)
weather_CIN['date'] = pd.to_datetime(weather_CIN['time'])
weather_CIN['location'] = 'Cincinnati'

weather_MIL = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Milwaukee_Brewers.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_MIL['date'] = pd.to_datetime(weather_MIL['time'])
weather_MIL['location'] = 'Milwaukee'

weather_STL = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/St_Louis_Cardinals.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_STL['date'] = pd.to_datetime(weather_STL['time'])
weather_STL['location'] = 'St. Louis'

weather_PIT = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Pittsburgh_Pirates.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_PIT['date'] = pd.to_datetime(weather_PIT['time'])
weather_PIT['location'] = 'Pittsburgh'

weather_nl_central = pd.concat([weather_CHC, weather_CIN, weather_MIL, weather_STL, weather_PIT], ignore_index=True)

weather_nl_central

,time,temperature_2m (°F),relative_humidity_2m (%),dew_point_2m (°F),precipitation (mm),rain (mm),snowfall (cm),cloud_cover (%),wind_speed_10m (mp/h),date,location
0,2005-04-03T00:00,35.1,76,28.3,0.0,0.0,0.0,0,5.4,2005-04-03 00:00:00,Chicago
1,2005-04-03T01:00,34.8,78,28.7,0.0,0.0,0.0,0,5.6,2005-04-03 01:00:00,Chicago
2,2005-04-03T02:00,34.2,79,28.4,0.0,0.0,0.0,0,5.8,2005-04-03 02:00:00,Chicago
3,2005-04-03T03:00,33.8,79,28.2,0.0,0.0,0.0,1,5.9,2005-04-03 03:00:00,Chicago
4,2005-04-03T04:00,33.5,80,28.0,0.0,0.0,0.0,0,5.4,2005-04-03 04:00:00,Chicago
...,...,...,...,...,...,...,...,...,...,...,...
482275,2016-04-03T19:00,42.3,58,28.6,0.0,0.0,0.0,2,9.1,2016-04-03 19:00:00,Pittsburgh
482276,2016-04-03T20:00,41.2,60,28.5,0.0,0.0,0.0,1,11.1,2016-04-03 20:00:00,Pittsburgh
482277,2016-04-03T21:00,41.7,60,28.7,0.0,0.0,0.0,47,10.7,2016-04-03 21:00:00,Pittsburgh
482278,2016-04-03T22:00,43.1,58,29.4,0.0,0.0,0.0,79,9.8,2016-04-03 22:00:00,Pittsburgh
482279,2016-04-03T23:00,45.1,56,30.2,0.0,0.0,0.0,48,12.4,2016-04-03 23:00:00,Pittsburgh

In [11]:
#read in weather data for NL West teams

weather_LAD = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Los_Angeles_Dodgers.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_LAD['date'] = pd.to_datetime(weather_LAD['time'])
weather_LAD['location'] = 'Los Angeles'

weather_SF = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/San_Francisco_Giants.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_SF['date'] = pd.to_datetime(weather_SF['time'])
weather_SF['location'] = 'San Francisco'

weather_SD = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/San_Diego_Padres.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_SD['date'] = pd.to_datetime(weather_SD['time'])
weather_SD['location'] = 'San Diego'

weather_ARI = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Arizona_Diamondbacks.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)
weather_ARI['date'] = pd.to_datetime(weather_ARI['time'])
weather_ARI['location'] = 'Arizona'

weather_COL = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/NL_TEAMS/Colorado_Rockies.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)

weather_COL['date'] = pd.to_datetime(weather_COL['time'])
weather_COL['location'] = 'Colorado'

weather_NL_west = pd.concat([weather_LAD, weather_SF, weather_SD, weather_ARI, weather_COL], ignore_index=True)

weather_NL_west

,time,temperature_2m (°F),relative_humidity_2m (%),dew_point_2m (°F),precipitation (mm),rain (mm),snowfall (cm),cloud_cover (%),wind_speed_10m (mp/h),date,location
0,2005-04-03T00:00,51.7,78,45.1,0.0,0.0,0.0,0,3.7,2005-04-03 00:00:00,Los Angeles
1,2005-04-03T01:00,51.0,78,44.3,0.0,0.0,0.0,0,4.0,2005-04-03 01:00:00,Los Angeles
2,2005-04-03T02:00,51.6,74,43.6,0.0,0.0,0.0,54,3.9,2005-04-03 02:00:00,Los Angeles
3,2005-04-03T03:00,50.6,74,42.6,0.0,0.0,0.0,57,2.4,2005-04-03 03:00:00,Los Angeles
4,2005-04-03T04:00,48.9,76,41.8,0.0,0.0,0.0,60,2.9,2005-04-03 04:00:00,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...
482275,2016-04-03T19:00,52.6,51,35.0,0.0,0.0,0.0,3,4.7,2016-04-03 19:00:00,Colorado
482276,2016-04-03T20:00,44.7,62,32.6,0.0,0.0,0.0,4,2.1,2016-04-03 20:00:00,Colorado
482277,2016-04-03T21:00,40.8,68,31.0,0.0,0.0,0.0,14,1.7,2016-04-03 21:00:00,Colorado
482278,2016-04-03T22:00,38.4,71,29.8,0.0,0.0,0.0,55,3.4,2016-04-03 22:00:00,Colorado
482279,2016-04-03T23:00,35.2,79,29.3,0.0,0.0,0.0,89,4.7,2016-04-03 23:00:00,Colorado

In [12]:
print(weather_NL_west['date'].dtype)

datetime64[ns]

In [13]:


weather_NL_west['time_of_day'] = weather_NL_west['date'].dt.hour.apply(lambda x: 'D' if 6 <= x < 18 else 'N')

merged_df = pd.merge(glogs, weather_NL_west, on='date', how='left')

merged_df = merged_df[merged_df['day_night'] == merged_df['time_of_day']]

merged_df.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,...,temperature_2m (°F),relative_humidity_2m (%),dew_point_2m (°F),precipitation (mm),rain (mm),snowfall (cm),cloud_cover (%),wind_speed_10m (mp/h),location_y,time_of_day
0,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,51.7,78.0,45.1,0.0,0.0,0.0,0.0,3.7,Los Angeles,N
1,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,50.3,76.0,43.0,0.0,0.0,0.0,95.0,13.1,San Francisco,N
2,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,55.8,96.0,54.5,0.0,0.0,0.0,41.0,3.0,San Diego,N
3,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,67.0,29.0,34.1,0.0,0.0,0.0,100.0,3.9,Arizona,N
4,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,34.8,72.0,26.8,0.0,0.0,0.0,99.0,3.2,Colorado,N

In [14]:
weather_nl_central['time_of_day'] = weather_nl_central['date'].dt.hour.apply(lambda x: 'D' if 6 <= x < 18 else 'N')

merged_df = pd.merge(glogs, weather_nl_central, on='date', how='left')

merged_df = merged_df[merged_df['day_night'] == merged_df['time_of_day']]

merged_df.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,...,temperature_2m (°F),relative_humidity_2m (%),dew_point_2m (°F),precipitation (mm),rain (mm),snowfall (cm),cloud_cover (%),wind_speed_10m (mp/h),location_y,time_of_day
0,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,35.1,76.0,28.3,0.0,0.0,0.0,0.0,5.4,Chicago,N
1,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,42.8,48.0,24.2,0.0,0.0,0.0,1.0,12.8,Cincinnati,N
2,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,33.6,77.0,27.2,0.0,0.0,0.0,0.0,6.5,Milwaukee,N
3,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,40.3,81.0,35.0,0.0,0.0,0.0,48.0,4.6,St. Louis,N
4,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,34.4,96.0,33.3,1.0,0.0,0.7,100.0,13.3,Pittsburgh,N

In [16]:
#read in weather data for AL East teams

weather_NYY = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/AL_TEAMS/New_York_Yankees.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)

weather_NYY['date'] = pd.to_datetime(weather_NYY['time'])

weather_NYY['location'] = 'New York'

weather_BOS = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/AL_TEAMS/Boston_Red_Sox.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)

weather_BOS['date'] = pd.to_datetime(weather_BOS['time'])

weather_BOS['location'] = 'Boston'

weather_BAL = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/AL_TEAMS/Baltimore_Orioles.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)

weather_BAL['date'] = pd.to_datetime(weather_BAL['time'])

weather_BAL['location'] = 'Baltimore'

weather_TOR = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/AL_TEAMS/Toronto_Blue_Jays.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)

weather_TOR['date'] = pd.to_datetime(weather_TOR['time'])

weather_TOR['location'] = 'Toronto'

weather_TMP = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/Chylle/MLB_Teams/AL_TEAMS/Tampa_Bay_Rays.csv',
    skiprows=3,  # Skips the first 3 rows of the file)
)   

weather_TMP['date'] = pd.to_datetime(weather_TMP['time'])

weather_TMP['location'] = 'Tampa Bay'


weather_AL_east = pd.concat([weather_NYY, weather_BOS, weather_BAL, weather_TOR, weather_TMP], ignore_index=True)

weather_AL_east.head()

HTTPError: HTTP Error 404: Not Found

In [49]:
# Merge NL East weather data with game logs
glogs_weather = pd.merge(glogs, weather_nl_east, on=['date', 'location'], how='left')
glogs_weather.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,day_night,park_id,attendance,location,temperature_2m_max (°F),rain_sum (inch)
0,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,9,N,Old Yankee Stadium,54818.0,New York,47.6,0.063
1,2005-04-04,2005,Mon,OAK,AL,1,BAL,AL,1,0,4,D,Camden Yards,48271.0,Baltimore,NaN,NaN
2,2005-04-04,2005,Mon,CLE,AL,1,CHW,AL,1,0,1,D,US Cellular Field,38141.0,Chicago,NaN,NaN
3,2005-04-04,2005,Mon,KC,AL,1,DET,AL,1,2,11,D,Comerica Park,44105.0,Detroit,NaN,NaN
4,2005-04-04,2005,Mon,MIN,AL,1,SEA,AL,1,1,5,D,Safeco Field,46249.0,Seattle,NaN,NaN

In [50]:
# Merge stadium capacity information with glogs
capacities = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/stadium_data.csv')
capacities.columns
glogs_weather_cap = pd.merge(glogs_weather, capacities, on=['park_id'], how='left')

# Convert capacity to float
glogs_weather_cap['capacity'] = glogs_weather_cap['capacity'].str.replace(',', '', regex=True)
glogs_weather_cap['capacity'] = glogs_weather_cap['capacity'].astype(float)

# Edit Progressive Field capacity - renovations after 2014 season decreased capacity from 43,000 to 35,225
glogs_weather_cap.loc[(glogs_weather_cap['park_id'] == 'Progressive Field') & (glogs_weather_cap['date'].dt.year<=2014), 'capacity'] = 43000


glogs_weather_cap.head()

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,day_night,park_id,attendance,location,temperature_2m_max (°F),rain_sum (inch),home team,capacity
0,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,9,N,Old Yankee Stadium,54818.0,New York,47.6,0.063,Yankees,56937.0
1,2005-04-04,2005,Mon,OAK,AL,1,BAL,AL,1,0,4,D,Camden Yards,48271.0,Baltimore,NaN,NaN,Orioles,45971.0
2,2005-04-04,2005,Mon,CLE,AL,1,CHW,AL,1,0,1,D,US Cellular Field,38141.0,Chicago,NaN,NaN,White Sox,40615.0
3,2005-04-04,2005,Mon,KC,AL,1,DET,AL,1,2,11,D,Comerica Park,44105.0,Detroit,NaN,NaN,Tigers,41083.0
4,2005-04-04,2005,Mon,MIN,AL,1,SEA,AL,1,1,5,D,Safeco Field,46249.0,Seattle,NaN,NaN,Mariners,47943.0

In [51]:
# Merge team performance data
team_performance = pd.read_csv('https://raw.githubusercontent.com/tmarchok1/DS440_project/refs/heads/main/team_performance.csv')
glogs_wcp = pd.merge(glogs_weather_cap, team_performance, on=['home team', 'year'], how='left')
glogs_wcp

,date,year,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,...,park_id,attendance,location,temperature_2m_max (°F),rain_sum (inch),home team,capacity,prev year wins,prev year WS,prev year division
0,2005-04-03,2005,Sun,BOS,AL,1,NYY,AL,1,2,...,Old Yankee Stadium,54818.0,New York,47.6,0.063,Yankees,56937.0,101.0,0.0,NaN
1,2005-04-04,2005,Mon,OAK,AL,1,BAL,AL,1,0,...,Camden Yards,48271.0,Baltimore,NaN,NaN,Orioles,45971.0,78.0,0.0,NaN
2,2005-04-04,2005,Mon,CLE,AL,1,CHW,AL,1,0,...,US Cellular Field,38141.0,Chicago,NaN,NaN,White Sox,40615.0,83.0,0.0,NaN
3,2005-04-04,2005,Mon,KC,AL,1,DET,AL,1,2,...,Comerica Park,44105.0,Detroit,NaN,NaN,Tigers,41083.0,72.0,0.0,NaN
4,2005-04-04,2005,Mon,MIN,AL,1,SEA,AL,1,1,...,Safeco Field,46249.0,Seattle,NaN,NaN,Mariners,47943.0,99.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29135,2016-10-02,2016,Sun,MIL,NL,162,COL,NL,162,6,...,Coors Field,27762.0,Colorado,NaN,NaN,Rockies,50144.0,68.0,0.0,NaN
29136,2016-10-02,2016,Sun,NYM,NL,162,PHI,NL,162,2,...,Citizens Bank Park,36935.0,Philadelphia,70.5,0.039,Phillies,43651.0,63.0,0.0,NaN
29137,2016-10-02,2016,Sun,LAD,NL,162,SF,NL,162,1,...,AT&T Park,41445.0,San Francisco,NaN,NaN,Giants,41915.0,84.0,0.0,NaN
29138,2016-10-02,2016,Sun,PIT,NL,162,STL,NL,162,4,...,Busch Stadium III,44615.0,St. Louis,NaN,NaN,Cardinals,45494.0,100.0,0.0,NaN
29139,2016-10-02,2016,Sun,MIA,NL,161,WSH,NL,162,7,...,Nationals Park,28730.0,"Washington, D.C.",71.7,0.000,Nationals,41339.0,83.0,0.0,NaN